[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.19"
remappings = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"]

# Base network configuration
[rpc_endpoints]
base_mainnet = "https://base-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
base_sepolia = "https://base-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"

[etherscan]
base = { key = "${BASESCAN_API_KEY}" }
base_sepolia = { key = "${BASESCAN_API_KEY}" }